package com.introvd.template.app.p177b;

/* renamed from: com.introvd.template.app.b.c */
public class C3743c {
    boolean blE = true;
    boolean blF = false;
    int blG = 0;
    int blH = 0;
    int blI = 0;
    boolean blJ = false;
    boolean blK = false;
    boolean blL = false;
    boolean blM = false;
    boolean blN = false;
    int blO = 1;
    int blP = 2;
    boolean blQ = true;
    int blR = 2;
    boolean blS = true;
    boolean blT = false;
    int blU = 2;
    int blV = 2;
    int blW = 2;
    int blX = 2;
    boolean blY = false;
    boolean blZ = false;
    int bmA = -1;
    String bmB;
    long bmC;
    int bmD = -1;
    int bmE = 70;
    float bmF = 1.0f;
    float bmG = 1.0f;
    float bmH = 1.0f;
    boolean bmI = true;
    String bmJ;
    boolean bmK = false;
    boolean bmL = false;
    boolean bmM = false;
    int bmN = 0;
    boolean bmO = false;
    boolean bmP = false;
    boolean bmQ = true;
    String bmR = "";
    boolean bmS = false;
    int bmT = 0;
    boolean bmU = false;
    int bmV = 2;
    String bmW = "";
    int bmX = 1;
    int bmY = 0;
    int bmZ = 0;
    int bma = 1;
    int bmb = -1;
    int bmc = 0;
    String bmd = "";
    String bme = "";
    int bmf = 1;
    int bmg = 0;
    int bmh = 1;
    int bmi = 0;
    int bmj = 2;
    int bmk = 3;
    int bml = 0;
    boolean bmm = false;
    int bmn = 1;
    int bmo = 1;
    int bmp = 0;
    boolean bmq = false;
    boolean bmr = false;
    boolean bms = true;
    boolean bmt = true;
    int bmu = 12;
    boolean bmv;
    boolean bmw;
    boolean bmx;
    boolean bmy;
    boolean bmz;
    public boolean bnA = false;
    public int bnB = 0;
    public int bnC = 0;
    public int bnD = 0;
    public String bnE;
    public int bnF = 0;
    public int bnG = 0;
    int bnH = 0;
    public String bnI;
    public int bnJ;
    public int bnK;
    public int bnL;
    public int bnM;
    public int bnN = 0;
    public int bnO = 1;
    int bna = -1;
    int bnb = 0;
    int bnc = 40;
    int bnd = 0;
    String bne;
    String bnf = "";
    boolean bng = true;
    boolean bnh = true;
    boolean bni = true;
    boolean bnj = false;
    int bnk = 0;
    int bnl = 0;
    int bnm = 0;
    int bnn = 0;
    int bno = 0;
    int bnp = 0;
    int bnq = 0;
    int bnr = 1;
    int bns = 20;
    int bnt = 0;
    int bnu = 0;
    int bnv = 0;
    int bnw = 0;
    String bnx;
    String bny;
    int bnz = 0;
    String feedbackOpenQQScheme;
    String feedbackQQNumber;
}
